- name: "Remove GitHub user {{ user_properties.username }} from {{ github_api_org }}"
  uri:
    url: "{{ github_api_url }}/orgs/{{ github_api_org }}/memberships/{{ user_properties.username }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ github_api_token }}"
    status_code:
      - 204
  no_log: true
