- name: "Update GitHub user {{ user_properties.username }} in GitHub Organization {{ github_api_org }}"
  uri:
    url: "{{ github_api_url }}/orgs/{{ github_api_org }}/memberships/{{user_properties.username}}"
    method: PUT
    headers:
      Authorization: "Bearer {{ github_api_token }}"
    body_format: json
    body:
      role: "{{ user_properties.role }}"
    status_code:
      - 200
  no_log: true
