---

- name: "Delete Contentful user {{ user_properties.email }}"
  uri:
    url: "{{ contentful_base_url }}/organizations/{{ contentful_org_id }}/organization_memberships/{{ contentful_user_org_membership_id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ contentful_access_token }}"
    status_code:
      - 204
  no_log: true
