---

- name: "Check if Contentful user {{ user_properties.email }} exists"
  uri:
    url: "{{ contentful_base_url }}/organizations/{{ contentful_org_id }}/users?query={{ user_properties.email }}"
    headers:
      Authorization: "Bearer {{ contentful_access_token }}"
  register: _contentful_user_search_response
  no_log: true

- set_fact:
    contentful_user_exists: "{{ _contentful_user_search_response | community.general.json_query('json.total') | int == 1 }}"
    contentful_user_id: "{{ _contentful_user_search_response | community.general.json_query('json.items[0].sys.id') | default(fallback_user_object.id) }}"
  vars:
    fallback_user_object:
      id: -1

- name: "Get Org Membership id of Contentful user {{ user_properties.email }}"
  uri:
    url: "{{ contentful_base_url }}/organizations/{{ contentful_org_id }}/organization_memberships?query={{ user_properties.email }}"
    headers:
      Authorization: "Bearer {{ contentful_access_token }}"
  register: _contentful_user_org_membership_id_search_response
  when: contentful_user_exists
  no_log: true

- set_fact:
    contentful_user_org_membership_id: "{{ _contentful_user_org_membership_id_search_response | community.general.json_query('json.items[0].sys.id') | default(fallback_user_object.id) }}"
    contentful_user_org_membership_version: "{{ _contentful_user_org_membership_id_search_response | community.general.json_query('json.items[0].sys.version') | default(fallback_user_object.version) }}"
  vars:
    fallback_user_object:
      id: -1
      version: 0

- name: "Get Space Membership id of Contentful user {{ user_properties.email }}"
  uri:
    url: "{{ contentful_base_url }}/organizations/{{ contentful_org_id }}/space_memberships?query={{ user_properties.email }}"
    headers:
      Authorization: "Bearer {{ contentful_access_token }}"
    status_code:
      - 200
      - 404
  register: _contentful_user_space_membership_id_search_response
  when: contentful_user_exists
  no_log: true

- set_fact:
    contentful_user_space_membership_id: "{{ _contentful_user_space_membership_id_search_response | community.general.json_query('json.items[0].sys.id') | default(fallback_user_object.id) }}"
    contentful_user_space_membership_version: "{{ _contentful_user_space_membership_id_search_response | community.general.json_query('json.items[0].sys.version') | default(fallback_user_object.version) }}"
  vars:
    fallback_user_object:
      id: -1
      version: 0
