- name: "Delete Azure user {{ user_properties.username }}"
  uri:
    url: "https://graph.microsoft.com/v1.0/users/{{user_properties.username}}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ azure_client_credentials.json.access_token }}"
    status_code:
      - 204
  when: user_properties is defined
