- name: "Check Azure user {{user_properties.username}}"
  uri:
    url: "https://graph.microsoft.com/v1.0/users/{{user_properties.username}}"
    method: GET
    headers:
      Authorization: "Bearer {{ azure_client_credentials.json.access_token }}"
    status_code:
      - 200
      - 404
  when: user_properties is defined
  register: azure_user_exists
