---

- name: "Delete AWS group {{ group_properties.displayName }}"
  uri:
    url: "{{ aws_api_url }}/Groups/{{ aws_group_id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ aws_api_token }}"
    status_code:
      - 204
  when: group_properties is defined
